# Generated by Django 5.0.6 on 2024-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
